/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 18:55:54 GMT 2018
 */

package com.liberty.upskill.Inheritance;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liberty.upskill.Inheritance.Person;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Person_ESTest extends Person_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Person person0 = new Person();
      person0.setPassport("CUP{R");
      String string0 = person0.getPassport();
      assertEquals("CUP{R", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Person person0 = new Person();
      person0.setPassport("");
      String string0 = person0.getPassport();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Person person0 = new Person();
      person0.setPanNo("O;lUw+\"*C");
      String string0 = person0.getPanNo();
      assertEquals("O;lUw+\"*C", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Person person0 = new Person();
      person0.setPanNo("");
      String string0 = person0.getPanNo();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Person person0 = new Person();
      String string0 = person0.getPanNo();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Person person0 = new Person();
      String string0 = person0.getPassport();
      assertNull(string0);
  }
}
