/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 18:54:45 GMT 2018
 */

package com.liberty.upskill.LinkedList;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liberty.upskill.LinkedList.LinkedListExample;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LinkedListExample_ESTest extends LinkedListExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      LinkedListExample.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedListExample linkedListExample0 = new LinkedListExample();
  }
}
