/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 18:56:41 GMT 2018
 */

package com.liberty.upskill.Overloading;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liberty.upskill.Overloading.StudentWithBankLoan;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StudentWithBankLoan_ESTest extends StudentWithBankLoan_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StudentWithBankLoan studentWithBankLoan0 = new StudentWithBankLoan();
      studentWithBankLoan0.calculateFees(2470.4121943, 1338.369460317892);
  }
}
