/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 18:57:42 GMT 2018
 */

package com.liberty.upskill.Overloading;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liberty.upskill.Overloading.DayScholar;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DayScholar_ESTest extends DayScholar_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DayScholar dayScholar0 = new DayScholar();
      dayScholar0.calculateFees(1.0);
      assertEquals(0, dayScholar0.getStudentId());
  }
}
