/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 18:57:56 GMT 2018
 */

package com.liberty.upskill.Overloading;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liberty.upskill.Overloading.MethodOverLoading;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MethodOverLoading_ESTest extends MethodOverLoading_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[0];
      MethodOverLoading.main(stringArray0);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MethodOverLoading methodOverLoading0 = new MethodOverLoading();
  }
}
