/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 18:57:27 GMT 2018
 */

package com.liberty.upskill.Inheritance;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liberty.upskill.Inheritance.InheritanceExample;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InheritanceExample_ESTest extends InheritanceExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InheritanceExample inheritanceExample0 = new InheritanceExample();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[4];
      InheritanceExample.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }
}
