/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 18:55:06 GMT 2018
 */

package com.liberty.upskill.Overriding;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liberty.upskill.Overriding.RegularCustomer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegularCustomer_ESTest extends RegularCustomer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegularCustomer regularCustomer0 = new RegularCustomer();
      regularCustomer0.purchaseAmount = 2665.1142684;
      regularCustomer0.calculateBill();
      assertNull(regularCustomer0.getCustomerName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RegularCustomer regularCustomer0 = new RegularCustomer();
      regularCustomer0.setCreditPoints((-2617));
      int int0 = regularCustomer0.getCreditPoints();
      assertEquals((-2617), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RegularCustomer regularCustomer0 = new RegularCustomer();
      regularCustomer0.purchaseAmount = 1681.0722358846;
      regularCustomer0.purchaseAmount = 2000.0;
      regularCustomer0.calculateBill();
      assertEquals(0, regularCustomer0.getCustomerNo());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RegularCustomer regularCustomer0 = new RegularCustomer();
      regularCustomer0.calculateBill();
      int int0 = regularCustomer0.getCreditPoints();
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RegularCustomer regularCustomer0 = new RegularCustomer();
      int int0 = regularCustomer0.getCreditPoints();
      assertEquals(0, int0);
  }
}
