/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 06 18:50:32 GMT 2018
 */

package com.liberty.upskill.VectorVsArrayList;

import org.junit.Test;
import static org.junit.Assert.*;
import com.liberty.upskill.VectorVsArrayList.ArrayListExample;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArrayListExample_ESTest extends ArrayListExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[0];
      ArrayListExample.main(stringArray0);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArrayListExample arrayListExample0 = new ArrayListExample();
  }
}
